from __future__ import annotations

# =============================================================================
# SOFT MANIPULATOR KINEMATICS  ->  BLENDER LIVE VISUALISER  + TARGET SIMULATION
# =============================================================================
#
# Python/Blender port of the MATLAB "New Soft Manipulator Kinematics" package.
# Models a 2 segment soft robot.
# Each segment: theta (bend angle / xi), phi (bend-plane orientation), beta (twist about local z), L (length).
#
# Derived from these MATLAB files:
#   transxyz.m, rx/ry/rz.m, rx_rad/ry_rad/rz_rad.m, rod_T.m, rod_T_twist.m,
#   FwdSRM.m, show_SoftManipulator.m, CoorPlot.m, Example_SoftManipulator_model.m
#
# CONTROLS (in the 3D viewport, after "Start Mouse Control"):
#   move mouse        -> bend active segment (left/right = phi, up/down = theta)
#   scroll wheel      -> twist (beta) of active segment
#   keys 1 / 2        -> choose which segment you are editing
#   R                 -> reset to the MATLAB example
#   Esc               -> stop control
#
# TARGET SIMULATION: green sphere(s) appear at random reachable
# spots; the end-effector tip must reach one to register it, after which a new
# target is placed. Reachable points are generated by sampling a random valid
# joint configuration and running forward kinematics (the same workspace-sampling
# idea used in Example_SoftManipulator_model.m), so every target is reachable.
#
# OBSTACLE COURSE: an optional cylinder or cuboid can be placed in the workspace.
# The robot body must be steered AROUND it to reach the target. The simulation
# continuously tests the robot backbone against the obstacle volume and reports
# contact (this is a measurement/telemetry feature, not a scored arcade game):
#   - the obstacle turns amber while any part of the body is inside it,
#   - a running count of contact events is displayed,
#   - by default a target only registers as reached when the body is clear of
#     the obstacle (toggle "target needs clear path" to change this).
#
# -----------------------------------------------------------------------------
# HOW THIS FILE IS ORGANISED (and how to read the section tags):
#   PART A = pure kinematics, a direct port of the MATLAB .m files. No Blender.
#   PART B = everything that talks to Blender (drawing, UI, mouse control, etc).
# Inside PART B each section is tagged so you can see its origin:
#   [MATLAB port: xxx.m] = draws/computes something defined in that .m file
#   [Blender only]       = pure Blender plumbing with no MATLAB equivalent
#                          (MATLAB drew straight to a figure; Blender instead
#                           needs persistent 3D objects, materials, operators)
# =============================================================================

from dataclasses import dataclass
import math
from typing import Iterable, Tuple

import numpy as np


# =============================================================================
# PART A — PURE KINEMATICS (no Blender). Direct port of the MATLAB .m functions.
# =============================================================================

@dataclass
class RobotParams:
    """Equivalent of the MATLAB `robot_params` struct: holds L (segment lengths)."""
    L: np.ndarray


def as_1d_array(values: Iterable[float], name: str) -> np.ndarray:
    arr = np.asarray(list(values), dtype=float).reshape(-1)
    if arr.size == 0:
        raise ValueError(f"{name} cannot be empty")
    return arr


# ---- transxyz.m ----
def transxyz(x: float, y: float, z: float) -> np.ndarray:
    return np.array(
        [[1.0, 0.0, 0.0, x],
         [0.0, 1.0, 0.0, y],
         [0.0, 0.0, 1.0, z],
         [0.0, 0.0, 0.0, 1.0]], dtype=float)


# ---- rx_rad.m / ry_rad.m / rz_rad.m ----  (radian input)
def rx_rad(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[1, 0, 0, 0], [0, c, -s, 0], [0, s, c, 0], [0, 0, 0, 1]], dtype=float)


def ry_rad(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[c, 0, s, 0], [0, 1, 0, 0], [-s, 0, c, 0], [0, 0, 0, 1]], dtype=float)


def rz_rad(theta: float) -> np.ndarray:
    c, s = math.cos(theta), math.sin(theta)
    return np.array([[c, -s, 0, 0], [s, c, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], dtype=float)


# ---- rx.m / ry.m / rz.m ----  (MATLAB used cosd/sind = DEGREE input, only for T_home)
def rx_deg(theta_deg: float) -> np.ndarray:
    return rx_rad(math.radians(theta_deg))


def ry_deg(theta_deg: float) -> np.ndarray:
    return ry_rad(math.radians(theta_deg))


def rz_deg(theta_deg: float) -> np.ndarray:
    return rz_rad(math.radians(theta_deg))


# ---- rod_T.m ----  constant-curvature transform across one segment
def rod_T(phi: float, xi: float, length: float, eps: float = 1e-9) -> np.ndarray:
    """Constant-curvature transform across one segment (rod_T.m).

    For xi≈0 the segment is straight, so it reduces to a translation of `length`
    along the local z-axis.
    """
    if abs(xi) < eps:
        return transxyz(0.0, 0.0, length)
    c2x = math.cos(2.0 * xi)
    s2x = math.sin(2.0 * xi)
    cp = math.cos(phi)
    sp = math.sin(phi)
    return np.array(
        [
            [c2x * cp**2 - cp**2 + 1.0, 0.5 * math.sin(2.0 * phi) * (c2x - 1.0), s2x * cp, (length * cp * math.sin(xi) ** 2) / xi],
            [0.5 * math.sin(2.0 * phi) * (c2x - 1.0), c2x * sp**2 - sp**2 + 1.0, s2x * sp, (length * sp * math.sin(xi) ** 2) / xi],
            [-s2x * cp, -s2x * sp, c2x, (length * math.sin(2.0 * xi)) / (2.0 * xi)],
            [0.0, 0.0, 0.0, 1.0],
        ], dtype=float)


# ---- rod_T_twist.m ----
def rod_T_twist(phi: float, xi: float, beta: float, length: float, eps: float = 1e-9) -> np.ndarray:
    """Port of rod_T_twist.m:  H2 = rod_T(phi,xi,l) * rz_rad(beta)."""
    return rod_T(phi, xi, length, eps=eps) @ rz_rad(beta)


# ---- shared `org` block (FwdSRM.m / show_SoftManipulator.m) ----
def home_transform(T_home: Iterable[float]) -> np.ndarray:
    h = as_1d_array(T_home, "T_home")
    if h.size != 6:
        raise ValueError("T_home must be [x, y, z, rx_deg, ry_deg, rz_deg]")
    org = transxyz(h[0], h[1], h[2])
    rot_org = rx_deg(h[3]) @ ry_deg(h[4]) @ rz_deg(h[5])
    org[0:3, 0:3] = rot_org[0:3, 0:3]
    return org


# ---- `segm_pos` block of show_SoftManipulator.m ----
def local_segment_backbone(phi: float, theta: float, beta: float, length: float,
                           n_points: int = 20, eps: float = 1e-9) -> np.ndarray:
    """
    Local (segment-frame) centreline points, shape (n_points, 3).

    R = L/(2*theta) is the closed form of the radius term in the r/R expression
    of show_SoftManipulator.m. beta does not appear here: twist does not bend the
    drawn tube, it only rotates the downstream frames.
    """
    if n_points < 2:
        raise ValueError("n_points must be >= 2")
    if abs(theta) < eps:
        z = np.linspace(0.0, length, n_points)
        return np.column_stack([np.zeros(n_points), np.zeros(n_points), z])
    rho = 2.0 * theta
    R = length / (2.0 * theta)
    rho_p = np.linspace(0.0, rho, n_points)
    x = (1.0 - np.cos(rho_p)) * R * math.cos(phi)
    y = (1.0 - np.cos(rho_p)) * R * math.sin(phi)
    z = R * np.sin(rho_p)
    return np.column_stack([x, y, z])


# ---- FwdSRM.m ----
def fwd_srm(theta, phi, beta, robot_params, T_home=(0, 0, 0, 0, 0, 0), sensor_L=5.0):
    """
    Serial chain: org * tr1 * T_disk * tr2 * T_disk * ... * T_sensor.
    Returns T (tip transform, includes sensor offset for nb>1) and TF (disk frames).
    """
    theta = as_1d_array(theta, "theta")
    phi = as_1d_array(phi, "phi")
    beta = as_1d_array(beta, "beta")
    L = as_1d_array(robot_params["L"] if isinstance(robot_params, dict) else robot_params.L, "L")

    nb = theta.size
    if not (phi.size == beta.size == L.size == nb):
        raise ValueError("theta, phi, beta, and L must have the same number of segments")

    T_disk = transxyz(0.0, 0.0, 3.0)
    T_sensor = transxyz(0.0, 0.0, sensor_L)
    org = home_transform(T_home)

    tr = np.zeros((nb, 4, 4), dtype=float)
    for i in range(nb):
        tr[i] = rod_T_twist(phi[i], theta[i], beta[i], L[i])

    TF = np.zeros((nb, 4, 4), dtype=float)
    T = None
    if nb == 1:
        T = org @ tr[0] @ T_disk
        TF[0] = T
        return T, TF
    for i in range(nb):
        if i == 0:
            T = org @ tr[i] @ T_disk
            TF[i] = T
        elif i != nb - 1:
            T = T @ tr[i] @ T_disk
            TF[i] = T
        else:
            T = T @ tr[i] @ T_disk
            TF[i] = T
            T = T @ T_sensor
    return T, TF


# ---- geometry half of show_SoftManipulator.m ----
def compute_backbone(theta, phi, beta, robot_params, T_home=(0, 0, 0, 0, 0, 0),
                     sensor_L=5.0, n_points_per_segment=20):
    """Returns (backbone_points (N,3), T tip transform, TF disk frames). Deterministic count."""
    theta = as_1d_array(theta, "theta")
    phi = as_1d_array(phi, "phi")
    beta = as_1d_array(beta, "beta")
    L = as_1d_array(robot_params["L"] if isinstance(robot_params, dict) else robot_params.L, "L")

    nb = theta.size
    if not (phi.size == beta.size == L.size == nb):
        raise ValueError("theta, phi, beta, and L must have the same number of segments")

    T, TF = fwd_srm(theta, phi, beta, {"L": L}, T_home=T_home, sensor_L=sensor_L)
    org = home_transform(T_home)

    global_points = []
    for i in range(nb):
        local = local_segment_backbone(phi[i], theta[i], beta[i], L[i], n_points=n_points_per_segment)
        local_h = np.column_stack([local, np.ones(local.shape[0])]).T
        X = (org if i == 0 else TF[i - 1]) @ local_h
        pts = X[0:3, :].T
        if i > 0:
            pts = pts[1:]
        global_points.append(pts)
        global_points.append(TF[i][0:3, 3].reshape(1, 3))  # bridge to disk centre
    return np.vstack(global_points), T, TF


def matlab_example_inputs():
    theta = np.radians([90.0, 90.0]) / 2.0
    phi = np.radians([0.0, 45.0])
    beta = np.radians([45.0, 0.0])
    robot_params = {"L": np.array([25.0, 25.0])}
    T_home = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    sensor_L = 5.0
    return theta, phi, beta, robot_params, T_home, sensor_L


# =============================================================================
# PART B — BLENDER VISUALISER + TARGET SIMULATION + OBSTACLE COURSE  [Blender]
# =============================================================================
# Everything here talks to Blender. It consumes the pure kinematics from Part A
# (which are the MATLAB ports) and turns the numbers into persistent 3D objects:
# a beveled curve for the backbone, an end-effector marker, optional coordinate
# frames, the reachable targets, and the obstacle. MATLAB drew straight to a
# figure; Blender needs real objects/materials/operators, so this half has no
# one-to-one MATLAB file -- each section is tagged with its origin instead.
#   mesh_get_or_add()      - fetch an object by name, or create it once
#   active_segment_props() - property names for the currently selected segment
#   handle_common_keys()   - 1/2 segment-select and R reset (used in mouse control)

import os
import sys
import random

import bpy
from mathutils import Vector

CURVE_NAME = "MATLAB_Matched_Soft_Robot_Centerline"
ROBOT_OBJECT_NAME = "MATLAB_Matched_Soft_Robot"
FRAME_OBJECT_PREFIX = "SR_Frame_"
EE_SHAFT_NAME = "SR_EndEffector_Shaft"
EE_TIP_NAME = "SR_EndEffector_Tip"
TARGET_PREFIX = "SR_Target_"
OBSTACLE_NAME = "SR_Obstacle"          # the single obstacle-course object
TIMER_INTERVAL_SECONDS = 0.03

RUN_SELFTEST = False

_targets = []  # module-level list of np.array([x, y, z]) target positions


# -----------------------------------------------------------------------------
# Scene properties                                                 [Blender only]
# -----------------------------------------------------------------------------
# Blender newcomer note: a "scene property" is a named setting attached to the
# Scene. Once registered here, each one (a) shows up as a slider/checkbox in the
# N-panel, (b) is saved inside the .blend file, and (c) is read in code as
# `scene.sr_theta1_deg`, etc. The "sr_" prefix ("soft robot") just keeps these
# from colliding with Blender's own scene attributes. FloatProperty = decimal,
# IntProperty = whole number, BoolProperty = checkbox, EnumProperty = dropdown.
def register_scene_properties():
    s = bpy.types.Scene

    s.sr_theta1_deg = bpy.props.FloatProperty(name="theta1 deg", default=90.0, min=-180.0, max=180.0)
    s.sr_phi1_deg = bpy.props.FloatProperty(name="phi1 deg", default=0.0, min=-180.0, max=180.0)
    s.sr_beta1_deg = bpy.props.FloatProperty(name="beta1 deg", default=45.0, min=-180.0, max=180.0)

    s.sr_theta2_deg = bpy.props.FloatProperty(name="theta2 deg", default=90.0, min=-180.0, max=180.0)
    s.sr_phi2_deg = bpy.props.FloatProperty(name="phi2 deg", default=45.0, min=-180.0, max=180.0)
    s.sr_beta2_deg = bpy.props.FloatProperty(name="beta2 deg", default=0.0, min=-180.0, max=180.0)

    # initializes segments and end effector, sets their lengths.

    s.sr_L1 = bpy.props.FloatProperty(name="L1", default=25.0, min=0.001)
    s.sr_L2 = bpy.props.FloatProperty(name="L2", default=25.0, min=0.001)
    s.sr_sensor_L = bpy.props.FloatProperty(name="sensor_L", default=5.0, min=0.0)

    s.sr_radius = bpy.props.FloatProperty(name="visual radius", default=5.5, min=0.01)
    s.sr_points_per_segment = bpy.props.IntProperty(name="points/segment", default=30, min=4, max=200)

    s.sr_live_update = bpy.props.BoolProperty(name="live update", default=False)
    s.sr_show_frames = bpy.props.BoolProperty(name="show debug frames", default=False)
    s.sr_show_end_effector = bpy.props.BoolProperty(name="show end-effector", default=True)

    # sr_mouse_sensitivity: default mouse sensitivity (0.3 degrees per pixel of motion)

    s.sr_twist_step = bpy.props.FloatProperty(name="twist step deg", default=2.0, min=0.1, max=20.0)
    s.sr_mouse_sensitivity = bpy.props.FloatProperty(name="mouse sensitivity (deg/px)", default=0.30, min=0.01, max=3.0)
    s.sr_active_segment = bpy.props.EnumProperty(
        name="active segment",
        items=[("1", "Segment 1", "Edit segment 1"), ("2", "Segment 2", "Edit segment 2")],
        default="1",
    )
    s.sr_mouse_control = bpy.props.BoolProperty(name="mouse control active", default=False)

    s.sr_target_sim_active = bpy.props.BoolProperty(name="target sim active", default=False)
    s.sr_target_count = bpy.props.IntProperty(name="target count", default=1, min=1, max=10)
    s.sr_target_radius = bpy.props.FloatProperty(name="target radius", default=3.0, min=0.1)
    s.sr_target_tolerance = bpy.props.FloatProperty(name="reach tolerance", default=8.0, min=0.1)
    # Neutral running tally of how many targets the tip has reached (not a game score).
    s.sr_target_score = bpy.props.IntProperty(name="targets reached", default=0)

    # ---- Obstacle course --------------------------------------------------
    # The obstacle is an upright primitive (axis aligned with world Z). The robot
    # must be maneuvered around it. Position/size are exposed so the researcher
    # can set up a specific scenario; contact is measured against these values.
    s.sr_obstacle_active = bpy.props.BoolProperty(name="enable obstacle", default=False)
    s.sr_obstacle_shape = bpy.props.EnumProperty(
        name="obstacle shape",
        items=[("CYLINDER", "Cylinder", "Upright cylinder"),
               ("CUBOID", "Cuboid", "Axis-aligned box")],
        default="CYLINDER",
    )
    s.sr_obstacle_x = bpy.props.FloatProperty(name="obstacle x", default=15.0)
    s.sr_obstacle_y = bpy.props.FloatProperty(name="obstacle y", default=0.0)
    s.sr_obstacle_z = bpy.props.FloatProperty(name="obstacle z (centre)", default=25.0)
    # For a cylinder this is the radius; for a cuboid it is the half-width in X and Y.
    s.sr_obstacle_radius = bpy.props.FloatProperty(name="obstacle radius / half-width", default=6.0, min=0.1)
    s.sr_obstacle_height = bpy.props.FloatProperty(name="obstacle height", default=30.0, min=0.1)
    # Extra safety gap added to the robot's own tube radius when testing contact.
    s.sr_obstacle_clearance = bpy.props.FloatProperty(name="contact clearance", default=0.0, min=0.0)
    # If True, a target only counts as reached while the body is clear of the obstacle.
    s.sr_require_clearance = bpy.props.BoolProperty(name="target needs clear path", default=True)
    # Running count of times the body newly entered the obstacle volume.
    s.sr_contact_count = bpy.props.IntProperty(name="contact events", default=0)


# -----------------------------------------------------------------------------
# Small shared helpers                                            [Blender only]
# -----------------------------------------------------------------------------
# Blender-side utilities with no MATLAB equivalent: they resolve which segment
# the UI is editing, create-or-reuse Blender objects, and interpret keyboard
# events during mouse control.
def active_segment_props(scene):
    """Return the (theta, phi, beta) property names for the active segment."""
    if scene.sr_active_segment == "1":
        return "sr_theta1_deg", "sr_phi1_deg", "sr_beta1_deg"
    return "sr_theta2_deg", "sr_phi2_deg", "sr_beta2_deg"


def mesh_get_or_add(name, add_fn):
    """Return an object by name, creating it via add_fn() if it doesn't exist yet."""
    obj = bpy.data.objects.get(name)
    if obj is None:
        add_fn()
        obj = bpy.context.object
        obj.name = name
    return obj


def handle_common_keys(scene, event, context):
    """Essential keys used during mouse control: 1/2 select segment, R reset.

    Returns True if the event was consumed.
    """
    if event.value != "PRESS":
        return False
    if event.type in {"ONE", "NUMPAD_1"}:
        scene.sr_active_segment = "1"
        return True
    if event.type in {"TWO", "NUMPAD_2"}:
        scene.sr_active_segment = "2"
        return True
    if event.type == "R":
        reset_to_matlab_example(scene)
        update_soft_robot(context)
        return True
    return False


# -----------------------------------------------------------------------------
# Scene inputs -> math                       [bridge: Blender UI -> Part A inputs]
# -----------------------------------------------------------------------------
# Converts the panel sliders into the exact argument form the MATLAB kinematics
# expect. Note the convention from Example_SoftManipulator_model.m: theta is
# passed as deg2rad(theta_deg)/2 (the panel shows the physical bend in degrees,
# halved here), while phi and beta are just deg2rad. reset_to_matlab_example
# restores the fixed example pose from that same MATLAB script.
def get_inputs_from_scene(scene):
    theta = [math.radians(scene.sr_theta1_deg) / 2.0, math.radians(scene.sr_theta2_deg) / 2.0]
    phi = [math.radians(scene.sr_phi1_deg), math.radians(scene.sr_phi2_deg)]
    beta = [math.radians(scene.sr_beta1_deg), math.radians(scene.sr_beta2_deg)]
    robot_params = {"L": [scene.sr_L1, scene.sr_L2]}
    T_home = [0, 0, 0, 0, 0, 0]
    return theta, phi, beta, robot_params, T_home, scene.sr_sensor_L


def compute_scene_robot(scene):
    theta, phi, beta, robot_params, T_home, sensor_L = get_inputs_from_scene(scene)
    return compute_backbone(theta=theta, phi=phi, beta=beta, robot_params=robot_params,
                            T_home=T_home, sensor_L=sensor_L,
                            n_points_per_segment=scene.sr_points_per_segment)

#generates the points that form the backbone of the robot segment. used in DRAW ROBOT SEGMENTS section

# resets parameters to default.
def reset_to_matlab_example(scene):
    scene.sr_theta1_deg, scene.sr_phi1_deg, scene.sr_beta1_deg = 90.0, 0.0, 45.0
    scene.sr_theta2_deg, scene.sr_phi2_deg, scene.sr_beta2_deg = 90.0, 45.0, 0.0


# -----------------------------------------------------------------------------
# DRAW ROBOT SEGMENTS      [Blender rendering of show_SoftManipulator.m output]
# -----------------------------------------------------------------------------
# MATLAB's show_SoftManipulator.m drew the backbone straight into a figure with
# line plots. Blender has no "plot" call, so instead we keep ONE persistent 3D
# object and just move its points each update (rather than deleting and
# rebuilding it every frame, which flickers and is slow).
#
# Blender newcomer note on the object we use:
#   - a "curve" is a path defined by control points;
#   - a "spline" is one such path inside the curve. We use a POLY spline, which
#     simply connects its points with straight lines (no smoothing) -- perfect,
#     because Part A already gives us many closely-spaced points along the arc;
#   - "bevel_depth" sweeps a circle along that path, turning the thin line into
#     a solid TUBE. In Blender bevel_depth is the tube RADIUS (not diameter).
def get_or_create_curve_object(scene, n_points):
    obj = bpy.data.objects.get(ROBOT_OBJECT_NAME)
    if obj is None:
        curve = bpy.data.curves.new(CURVE_NAME, type="CURVE")
        curve.dimensions = "3D"
        curve.resolution_u = 2
        curve.fill_mode = "FULL"
        curve.splines.new(type="POLY").points.add(n_points - 1)
        obj = bpy.data.objects.new(ROBOT_OBJECT_NAME, curve)
        bpy.context.collection.objects.link(obj) #actually visualizes the object in the scene

    curve = obj.data
    curve.bevel_depth = scene.sr_radius      # bevel_depth = sets tube RADIUS in Blender (derived from scene input)
    curve.bevel_resolution = 12
    if len(curve.splines) == 0:
        curve.splines.new(type="POLY").points.add(n_points - 1)
    spline = curve.splines[0]
    current = len(spline.points)
    if current < n_points:
        spline.points.add(n_points - current)
    elif current > n_points:                     # POLY can't drop points -> rebuild
        curve.splines.clear()
        curve.splines.new(type="POLY").points.add(n_points - 1)
    return obj


def update_curve_points(obj, points):
    for p, xyz in zip(obj.data.splines[0].points, points):
        p.co = (float(xyz[0]), float(xyz[1]), float(xyz[2]), 1.0)


# -----------------------------------------------------------------------------
# Mesh shape helpers (cylinders, cones, spheres, boxes)            [Blender only]
# -----------------------------------------------------------------------------
# These build the small solid shapes used for the coordinate frames, the
# end-effector, the targets, and the obstacle -- NOT the robot body (that is the
# beveled spline above). Each helper follows the same recipe:
#   1. create-or-reuse a named object (via mesh_get_or_add), then
#   2. reposition/resize it in place on every later call.
# Blender newcomer note: Blender makes cylinders/cones standing up along their
# own local +Z. `to_track_quat("Z","Y")` builds the rotation that aims that
# local Z along whatever direction vector we computed, so a shape can lie
# between two arbitrary points. Setting `obj.dimensions` resizes via the
# bounding box (diameter x diameter x length), which is why radius is doubled.
def assign_color(obj, mat_name, rgba):
    mat = bpy.data.materials.get(mat_name)
    if mat is None:
        mat = bpy.data.materials.new(mat_name)
        mat.diffuse_color = rgba
    if obj.data.materials:
        obj.data.materials[0] = mat
    else:
        obj.data.materials.append(mat)


def make_cylinder_between(name, start, end, radius=0.25):
    start, end = Vector(start), Vector(end)
    direction = end - start
    length = direction.length
    if length < 1e-9:
        return None
    mid = (start + end) / 2.0
    obj = mesh_get_or_add(name, lambda: bpy.ops.mesh.primitive_cylinder_add(
        vertices=12, radius=radius, depth=length, location=mid))
    obj.location = mid
    obj.dimensions = (radius * 2.0, radius * 2.0, length)
    obj.rotation_euler = direction.to_track_quat("Z", "Y").to_euler()
    return obj


def make_cone_along(name, base, direction, length, radius):
    base, d = Vector(base), Vector(direction)
    if d.length < 1e-9 or length < 1e-9:
        return None
    d = d.normalized()
    center = base + d * (length / 2.0)
    obj = mesh_get_or_add(name, lambda: bpy.ops.mesh.primitive_cone_add(
        vertices=16, radius1=radius, radius2=0.0, depth=length, location=center))
    obj.location = center
    obj.dimensions = (radius * 2.0, radius * 2.0, length)
    obj.rotation_euler = d.to_track_quat("Z", "Y").to_euler()
    return obj


def make_sphere(name, pos, radius):
    loc = (float(pos[0]), float(pos[1]), float(pos[2]))
    obj = mesh_get_or_add(name, lambda: bpy.ops.mesh.primitive_uv_sphere_add(radius=radius, location=loc))
    obj.location = loc
    obj.dimensions = (radius * 2.0, radius * 2.0, radius * 2.0)
    return obj


def make_upright_cylinder(name, center, radius, height):
    """A cylinder standing along world Z, centred at `center`. Used for the
    cylindrical obstacle. No rotation is needed because it stays upright."""
    cx, cy, cz = float(center[0]), float(center[1]), float(center[2])
    obj = mesh_get_or_add(name, lambda: bpy.ops.mesh.primitive_cylinder_add(
        vertices=24, radius=radius, depth=height, location=(cx, cy, cz)))
    obj.location = (cx, cy, cz)
    obj.dimensions = (radius * 2.0, radius * 2.0, height)
    obj.rotation_euler = (0.0, 0.0, 0.0)
    return obj


def make_box(name, center, size):
    """An axis-aligned box centred at `center` with full dimensions `size`
    (sx, sy, sz). Used for the cuboidal obstacle. primitive_cube_add makes a
    unit cube; setting `dimensions` then stretches it to the requested size."""
    cx, cy, cz = float(center[0]), float(center[1]), float(center[2])
    obj = mesh_get_or_add(name, lambda: bpy.ops.mesh.primitive_cube_add(
        size=1.0, location=(cx, cy, cz)))
    obj.location = (cx, cy, cz)
    obj.dimensions = (float(size[0]), float(size[1]), float(size[2]))
    obj.rotation_euler = (0.0, 0.0, 0.0)
    return obj


def delete_by_prefix(prefix):
    for obj in list(bpy.context.scene.objects):
        if obj.name.startswith(prefix):
            bpy.data.objects.remove(obj, do_unlink=True)


# -----------------------------------------------------------------------------
# Coordinate frames                                     [MATLAB port: CoorPlot.m]
# -----------------------------------------------------------------------------
# CoorPlot.m drew little RGB axis triads at each frame. Here we draw the same
# thing with three thin colored cylinders (X=red, Y=green, Z=blue) per disk
# frame in TF. Purely a visualization aid; toggle with "show debug frames".
def update_frames(TF, scale=6.0):
    axes = (("X", 0, (1.0, 0.05, 0.05, 1.0)),
            ("Y", 1, (0.05, 1.0, 0.05, 1.0)),
            ("Z", 2, (0.1, 0.3, 1.0, 1.0)))
    for i, T in enumerate(TF):
        origin = T[0:3, 3]
        for label, col, color in axes:
            obj = make_cylinder_between(f"{FRAME_OBJECT_PREFIX}{i+1}_{label}",
                                        origin, origin + T[0:3, col] * scale, radius=0.15)
            if obj:
                assign_color(obj, f"SR_axis_{label}", color)


# -----------------------------------------------------------------------------
# End effector          [MATLAB port: show_SoftManipulator.m red sensor line
#                        + Blender-only orange cone tip]
# -----------------------------------------------------------------------------
# In show_SoftManipulator.m the tip is drawn as a single thick red line from the
# last backbone point to T (the sensor transform): line(...,'Color','r',
# 'LineWidth',4). We reproduce that as the red shaft here. The orange cone is a
# Blender-only addition: it marks the tip position AND points along the tip's
# local Z, so you can see which way the end effector is facing.
def update_end_effector(T, TF, scene):
    tip = np.asarray(T[0:3, 3], dtype=float)
    tip_z = np.asarray(T[0:3, 2], dtype=float)
    nrm = np.linalg.norm(tip_z)
    if nrm > 1e-9:
        tip_z = tip_z / nrm
    last_disk = np.asarray(TF[-1][0:3, 3], dtype=float)

    if np.linalg.norm(tip - last_disk) > 1e-6:
        shaft = make_cylinder_between(EE_SHAFT_NAME, last_disk, tip, radius=max(scene.sr_radius * 0.35, 0.2))
        if shaft:
            assign_color(shaft, "SR_EE_red", (0.9, 0.08, 0.08, 1.0))
    else:
        delete_by_prefix(EE_SHAFT_NAME)

    cone = make_cone_along(EE_TIP_NAME, tip, tip_z,
                           length=max(scene.sr_radius * 2.2, 6.0),
                           radius=max(scene.sr_radius * 0.9, 0.5))
    if cone:
        assign_color(cone, "SR_EE_orange", (1.0, 0.45, 0.0, 1.0))


# -----------------------------------------------------------------------------
# TARGET SIMULATION              [Blender only; target positions use FwdSRM.m]
# -----------------------------------------------------------------------------
# Targets are green spheres placed at reachable points in the workspace. The
# researcher steers the tip to a target; reaching it (within a tolerance)
# registers it and a new target is placed. Positions come from forward
# kinematics on a random valid joint configuration, so every target is
# guaranteed reachable. When an obstacle is enabled, target points that fall
# inside the obstacle are rejected so the task stays feasible.
def random_reachable_tip(scene, avoid_obstacle=True, max_tries=25):
    """Sample a random valid joint config and return its tip (always reachable).

    If an obstacle is active, resample up to `max_tries` times to avoid placing
    a target inside the obstacle volume (so the target is not unreachable
    without contact). Falls back to the last sample if all attempts fail.
    """
    tip = None
    for _ in range(max_tries):
        th = [math.radians(random.uniform(0.0, 90.0)) / 2.0 for _ in range(2)]
        ph = [math.radians(random.uniform(-180.0, 180.0)) for _ in range(2)]
        bt = [math.radians(random.uniform(-45.0, 45.0)) for _ in range(2)]
        T, _ = fwd_srm(th, ph, bt, {"L": [scene.sr_L1, scene.sr_L2]},
                       T_home=[0, 0, 0, 0, 0, 0], sensor_L=scene.sr_sensor_L)
        tip = np.asarray(T[0:3, 3], dtype=float)
        if not (avoid_obstacle and scene.sr_obstacle_active):
            return tip
        # Keep the target clear of the obstacle by at least the target's own radius.
        if not point_in_obstacle(tip, scene, extra=scene.sr_target_radius):
            return tip
    return tip


def update_targets(T, scene, in_contact):
    """Keep `target count` targets alive; register any the tip reaches; redraw.

    `in_contact` is True when the robot body is currently intersecting the
    obstacle. If "target needs clear path" is on, a target is only registered
    while the body is clear -- this is what forces maneuvering AROUND the
    obstacle rather than pushing through it.
    """
    while len(_targets) < scene.sr_target_count:
        _targets.append(random_reachable_tip(scene))
    while len(_targets) > scene.sr_target_count:
        _targets.pop()

    tip = np.asarray(T[0:3, 3], dtype=float)
    blocked = in_contact and scene.sr_require_clearance
    for i in range(len(_targets)):
        if np.linalg.norm(tip - _targets[i]) <= scene.sr_target_tolerance:
            if blocked:
                # Tip is at the target but the body is inside the obstacle:
                # do not register this reach; the path was not clear.
                continue
            _targets[i] = random_reachable_tip(scene)
            scene.sr_target_score += 1
            print(f"[sim] target reached; total reached = {scene.sr_target_score}")

    delete_by_prefix(TARGET_PREFIX)
    for i, pos in enumerate(_targets):
        assign_color(make_sphere(f"{TARGET_PREFIX}{i}", pos, scene.sr_target_radius),
                     "SR_target_mat", (0.1, 0.9, 0.2, 1.0))


# -----------------------------------------------------------------------------
# OBSTACLE COURSE                                                  [Blender only]
# -----------------------------------------------------------------------------
# An optional cylinder or cuboid the robot must be steered around. We model it
# analytically (an upright primitive aligned with world Z) and test the robot's
# backbone points against that volume. The obstacle is inflated by the robot's
# own tube radius plus a clearance margin, so "contact" means the visible tube
# would touch the visible obstacle, not just the infinitely-thin centreline.
#
# Assumptions (documented so results are interpretable):
#   - the obstacle is axis-aligned and upright (no tilt);
#   - `radius` is the cylinder radius, or the cuboid half-width in X and Y;
#   - `height` is the full extent along Z, centred on obstacle z.
def point_in_obstacle(p, scene, extra=0.0):
    """True if point `p` lies inside the obstacle volume, expanded by `extra`."""
    ox, oy, oz = scene.sr_obstacle_x, scene.sr_obstacle_y, scene.sr_obstacle_z
    radius = scene.sr_obstacle_radius
    half_h = scene.sr_obstacle_height / 2.0
    dz = abs(float(p[2]) - oz)
    if dz > half_h + extra:
        return False
    if scene.sr_obstacle_shape == "CYLINDER":
        dxy = math.hypot(float(p[0]) - ox, float(p[1]) - oy)
        return dxy <= radius + extra
    # CUBOID
    return abs(float(p[0]) - ox) <= radius + extra and abs(float(p[1]) - oy) <= radius + extra


def backbone_contacts_obstacle(points, scene):
    """Vectorized test: does ANY backbone point lie inside the obstacle volume,
    inflated by (robot tube radius + clearance)? Returns a bool."""
    if not scene.sr_obstacle_active:
        return False
    ox, oy, oz = scene.sr_obstacle_x, scene.sr_obstacle_y, scene.sr_obstacle_z
    radius = scene.sr_obstacle_radius
    half_h = scene.sr_obstacle_height / 2.0
    margin = scene.sr_radius + scene.sr_obstacle_clearance  # tube half-thickness + safety gap
    pts = np.asarray(points, dtype=float)
    dz = np.abs(pts[:, 2] - oz)
    within_z = dz <= half_h + margin
    if scene.sr_obstacle_shape == "CYLINDER":
        dxy = np.hypot(pts[:, 0] - ox, pts[:, 1] - oy)
        inside = within_z & (dxy <= radius + margin)
    else:  # CUBOID
        inside = (within_z
                  & (np.abs(pts[:, 0] - ox) <= radius + margin)
                  & (np.abs(pts[:, 1] - oy) <= radius + margin))
    return bool(np.any(inside))


def update_obstacle(scene, in_contact):
    """Create/update the obstacle object at its configured pose and shape, and
    color it grey when clear or amber while the body is in contact.

    If the shape enum changed since last time, the old object is removed first
    so the correct primitive (cylinder vs box) is rebuilt."""
    shape = scene.sr_obstacle_shape
    center = (scene.sr_obstacle_x, scene.sr_obstacle_y, scene.sr_obstacle_z)
    radius = scene.sr_obstacle_radius
    height = scene.sr_obstacle_height

    existing = bpy.data.objects.get(OBSTACLE_NAME)
    if existing is not None and existing.get("sr_shape", "") != shape:
        bpy.data.objects.remove(existing, do_unlink=True)

    if shape == "CYLINDER":
        obj = make_upright_cylinder(OBSTACLE_NAME, center, radius, height)
    else:  # CUBOID: full dims are (2*half-width, 2*half-width, height)
        obj = make_box(OBSTACLE_NAME, center, (radius * 2.0, radius * 2.0, height))
    obj["sr_shape"] = shape  # remember which primitive we built

    if in_contact:
        assign_color(obj, "SR_obstacle_contact", (0.95, 0.55, 0.1, 1.0))  # amber
    else:
        assign_color(obj, "SR_obstacle_clear", (0.5, 0.5, 0.55, 1.0))     # neutral grey
    return obj


# -----------------------------------------------------------------------------
# Main update                                                     [Blender only]
# -----------------------------------------------------------------------------
# Called on every change (button, key, mouse move, or the live timer). It runs
# the Part A kinematics for the current scene inputs, then refreshes every
# visual: the robot tube, the debug frames, the end-effector, the obstacle, and
# the targets. Everything downstream reads from the same points/T/TF so the
# picture is always self-consistent.
def update_soft_robot(context=None):
    scene = bpy.context.scene if context is None else context.scene
    points, T, TF = compute_scene_robot(scene)

    obj = get_or_create_curve_object(scene, len(points))
    update_curve_points(obj, points)

    update_frames(TF) if scene.sr_show_frames else delete_by_prefix(FRAME_OBJECT_PREFIX)

    if scene.sr_show_end_effector:
        update_end_effector(T, TF, scene)
    else:
        delete_by_prefix(EE_SHAFT_NAME)
        delete_by_prefix(EE_TIP_NAME)

    # --- Obstacle course: test the body against the obstacle, then draw it. ---
    in_contact = backbone_contacts_obstacle(points, scene)
    if scene.sr_obstacle_active:
        update_obstacle(scene, in_contact)
        # Count a "contact event" only on the rising edge (clear -> contact),
        # not every frame the body stays inside, so the tally is meaningful.
        was_in_contact = bool(scene.get("_sr_was_in_contact", False))
        if in_contact and not was_in_contact:
            scene.sr_contact_count += 1
            print(f"[sim] body entered obstacle volume; contact events = {scene.sr_contact_count}")
        scene["_sr_was_in_contact"] = in_contact
    else:
        delete_by_prefix(OBSTACLE_NAME)
        scene["_sr_was_in_contact"] = False

    # --- Targets: reaching one requires a clear path when the obstacle is on. ---
    if scene.sr_target_sim_active:
        update_targets(T, scene, in_contact)
    else:
        delete_by_prefix(TARGET_PREFIX)
        _targets.clear()

    obj["tip_x"], obj["tip_y"], obj["tip_z"] = float(T[0, 3]), float(T[1, 3]), float(T[2, 3])
    return obj


def live_update_timer():
    if bpy.context.scene.sr_live_update:
        update_soft_robot()
        return TIMER_INTERVAL_SECONDS
    return None


# -----------------------------------------------------------------------------
# Operators                                                       [Blender only]
# -----------------------------------------------------------------------------
# Blender newcomer note: an "Operator" is an action Blender can run -- it is what
# sits behind a button or a menu item. `bl_idname` is its unique call name (used
# as layout.operator("soft_robot.update")) and `bl_label` is the button text.
# `execute()` runs once when clicked. A "modal" operator (see mouse control
# below) is special: after starting it keeps receiving live events (mouse moves,
# key presses) via `modal()` until it returns CANCELLED/FINISHED -- that is how
# we get real-time control inside the viewport.
class SR_OT_Update(bpy.types.Operator):
    bl_idname = "soft_robot.update"
    bl_label = "Update Soft Robot"

    def execute(self, context):
        update_soft_robot(context)
        return {"FINISHED"}


class SR_OT_StartLive(bpy.types.Operator):
    bl_idname = "soft_robot.start_live"
    bl_label = "Start Live Update"

    def execute(self, context):
        context.scene.sr_live_update = True
        if not bpy.app.timers.is_registered(live_update_timer):
            bpy.app.timers.register(live_update_timer)
        return {"FINISHED"}


class SR_OT_StopLive(bpy.types.Operator):
    bl_idname = "soft_robot.stop_live"
    bl_label = "Stop Live Update"

    def execute(self, context):
        context.scene.sr_live_update = False
        return {"FINISHED"}


class SR_OT_MouseControl(bpy.types.Operator):
    """Move the mouse (no button held) to bend the active segment."""
    bl_idname = "soft_robot.mouse_control"
    bl_label = "Start Mouse Control"
    bl_description = "Move mouse to bend (L/R=phi, U/D=theta); wheel=twist; 1/2 select; R reset; Esc stop"

    def execute(self, context):
        context.scene.sr_mouse_control = True
        context.window_manager.modal_handler_add(self)
        self.report({"INFO"}, "Mouse control on: move to bend, wheel=twist, 1/2 select, R reset, Esc stop")
        return {"RUNNING_MODAL"}

    def modal(self, context, event):
        scene = context.scene
        if not scene.sr_mouse_control:
            return {"CANCELLED"}
        if event.type == "ESC":
            scene.sr_mouse_control = False
            self.report({"INFO"}, "Mouse control stopped")
            return {"CANCELLED"}
        if handle_common_keys(scene, event, context):
            return {"RUNNING_MODAL"}

        theta_name, phi_name, beta_name = active_segment_props(scene)

        if event.value == "PRESS" and event.type == "WHEELUPMOUSE":
            setattr(scene, beta_name, getattr(scene, beta_name) + scene.sr_twist_step)
            update_soft_robot(context)
            return {"RUNNING_MODAL"}
        if event.value == "PRESS" and event.type == "WHEELDOWNMOUSE":
            setattr(scene, beta_name, getattr(scene, beta_name) - scene.sr_twist_step)
            update_soft_robot(context)
            return {"RUNNING_MODAL"}

        # Move-to-bend: any mouse motion bends the active segment (no button needed).
        if event.type == "MOUSEMOVE":
            dx = event.mouse_x - event.mouse_prev_x
            dy = event.mouse_y - event.mouse_prev_y
            if dx == 0 and dy == 0:
                return {"PASS_THROUGH"}
            sens = scene.sr_mouse_sensitivity
            new_phi = ((getattr(scene, phi_name) + dx * sens + 180.0) % 360.0) - 180.0
            setattr(scene, phi_name, new_phi)
            setattr(scene, theta_name, max(0.0, min(180.0, getattr(scene, theta_name) + dy * sens)))
            update_soft_robot(context)
            return {"PASS_THROUGH"}

        return {"PASS_THROUGH"}


class SR_OT_StopMouseControl(bpy.types.Operator):
    bl_idname = "soft_robot.stop_mouse_control"
    bl_label = "Stop Mouse Control"

    def execute(self, context):
        context.scene.sr_mouse_control = False
        return {"FINISHED"}


class SR_OT_StartTargetSim(bpy.types.Operator):
    bl_idname = "soft_robot.start_target_sim"
    bl_label = "Start Target Simulation"
    bl_description = "Spawn random reachable targets"

    def execute(self, context):
        scene = context.scene
        scene.sr_target_sim_active = True
        scene.sr_target_score = 0      # reset the reached tally for a fresh run
        scene.sr_contact_count = 0     # reset contact telemetry too
        scene["_sr_was_in_contact"] = False
        _targets.clear()
        update_soft_robot(context)
        return {"FINISHED"}


class SR_OT_StopTargetSim(bpy.types.Operator):
    bl_idname = "soft_robot.stop_target_sim"
    bl_label = "Stop Target Simulation"

    def execute(self, context):
        context.scene.sr_target_sim_active = False
        delete_by_prefix(TARGET_PREFIX)
        _targets.clear()
        return {"FINISHED"}


# -----------------------------------------------------------------------------
# Panel                                                           [Blender only]
# -----------------------------------------------------------------------------
# Blender newcomer note: a "Panel" is the box of controls in the viewport's
# N-panel (press N in the 3D view, then the "Soft Robot" tab). `draw()` runs
# every redraw and lays out rows: `layout.prop(scene, "x")` draws the widget for
# a scene property, and `layout.operator("id")` draws a button that runs an
# operator. It only describes the UI; the real work lives in the operators.
class SR_PT_Panel(bpy.types.Panel):
    bl_label = "Soft Robot MATLAB Match"
    bl_idname = "SR_PT_panel"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"
    bl_category = "Soft Robot"

    def draw(self, context):
        layout = self.layout
        scene = context.scene

        layout.label(text="Segment 1")
        for prop in ("sr_theta1_deg", "sr_phi1_deg", "sr_beta1_deg", "sr_L1"):
            layout.prop(scene, prop)

        layout.separator()
        layout.label(text="Segment 2")
        for prop in ("sr_theta2_deg", "sr_phi2_deg", "sr_beta2_deg", "sr_L2"):
            layout.prop(scene, prop)

        layout.separator()
        for prop in ("sr_sensor_L", "sr_radius", "sr_points_per_segment",
                     "sr_show_frames", "sr_show_end_effector",
                     "sr_active_segment", "sr_twist_step", "sr_mouse_sensitivity"):
            layout.prop(scene, prop)

        layout.separator()
        layout.operator("soft_robot.update")
        row = layout.row()
        row.operator("soft_robot.start_live")
        row.operator("soft_robot.stop_live")
        layout.prop(scene, "sr_live_update")

        layout.separator()
        layout.label(text="Target simulation")
        row = layout.row()
        row.operator("soft_robot.start_target_sim")
        row.operator("soft_robot.stop_target_sim")
        for prop in ("sr_target_count", "sr_target_radius", "sr_target_tolerance"):
            layout.prop(scene, prop)
        layout.label(text=f"Targets reached: {scene.sr_target_score}")

        layout.separator()
        layout.label(text="Obstacle course")
        layout.prop(scene, "sr_obstacle_active")
        layout.prop(scene, "sr_obstacle_shape")
        row = layout.row()
        row.prop(scene, "sr_obstacle_x")
        row.prop(scene, "sr_obstacle_y")
        row.prop(scene, "sr_obstacle_z")
        layout.prop(scene, "sr_obstacle_radius")
        layout.prop(scene, "sr_obstacle_height")
        layout.prop(scene, "sr_obstacle_clearance")
        layout.prop(scene, "sr_require_clearance")
        # Live telemetry: current contact state and cumulative contact events.
        status = "CONTACT" if scene.get("_sr_was_in_contact", False) else "clear"
        layout.label(text=f"Body status: {status}")
        layout.label(text=f"Contact events: {scene.sr_contact_count}")

        layout.separator()
        layout.label(text="Mouse control")
        row = layout.row()
        row.operator("soft_robot.mouse_control")
        row.operator("soft_robot.stop_mouse_control")
        layout.label(text="Move mouse: L/R=phi, U/D=theta | wheel=twist | 1/2 select | R reset | Esc stop")


classes = [
    SR_OT_Update, SR_OT_StartLive, SR_OT_StopLive,
    SR_OT_MouseControl, SR_OT_StopMouseControl,
    SR_OT_StartTargetSim, SR_OT_StopTargetSim,
    SR_PT_Panel,
]


def register():
    register_scene_properties()
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)


if __name__ == "__main__":
    if RUN_SELFTEST:
        theta, phi, beta, robot_params, T_home, sensor_L = matlab_example_inputs()
        points, T, TF = compute_backbone(theta, phi, beta, robot_params, T_home, sensor_L, n_points_per_segment=10)
        np.set_printoptions(precision=6, suppress=True)
        print("Backbone points:\n", points)
        print("\nFinal T:\n", T)
        print("\nSegment TF:\n", TF)

    try:
        unregister()
    except Exception:
        pass
    register()
    update_soft_robot()
    print("Soft robot loaded. Viewport > N panel > Soft Robot.")
    print("Start Mouse Control, then optionally enable the obstacle and Start Target Simulation.")